# Practice 1. 뉴스 분류 하기

데이터 셋 출처: https://github.com/KLUE-benchmark/KLUE

뉴스 제목을 보고, 어느 분야의 뉴스인지 분류하는 모델을 만들어보세요.

In [31]:
import pandas as pd

train_df = pd.read_csv("./data/news_train.csv")
val_df = pd.read_csv("./data/news_val.csv")

In [32]:
train_df

                                   text  label
0            유튜브 내달 2일까지 크리에이터 지원 공간 운영      3
1               어버이날 맑다가 흐려져…남부지방 옅은 황사      3
2           내년부터 국가RD 평가 때 논문건수는 반영 않는다      2
3       김명자 신임 과총 회장 원로와 젊은 과학자 지혜 모을 것      2
4        회색인간 작가 김동식 양심고백 등 새 소설집 2권 출간      3
...                                 ...    ...
45673      사우디 아람코 주요 석유시설·유전 드론 공격에 화재      4
45674    박기원 감독 눈치 보지 말고…비예나 눈치 본 건 아닌데      5
45675  아시안게임 첫 경기 앞둔 라건아 인도네시아 팬이라도 ...      5
45676     트럼프 미중 무역협상 1단계 합의 서명식 가질 것종합      4
45677  극적 역전승 도로공사 GS칼텍스 꺾고 2년 연속 챔프...      5

[45678 rows x 2 columns]

In [33]:
val_df

                                    text  label
0           5억원 무이자 융자는 되고 7천만원 이사비는 안된다      2
1      왜 수소충전소만 더 멀리 떨어져야 하나 한경연 규제개혁 건의      2
2             항응고제 성분 코로나19에 효과…세포실험서 확인      0
3       실거래가 가장 비싼 역세권은 신반포역…3.3㎡당 1억 육박      1
4                       기자회견 하는 성 소수자 단체      2
...                                  ...    ...
9102        KB금융 미국 IB 스티펠과 제휴…선진국 시장 공략      1
9103     1보 서울시교육청 신종코로나 확산에 개학 연기·휴업 검토      2
9104         게시판 키움증권 2020 키움 영웅전 실전투자대회      1
9105                   답변하는 배기동 국립중앙박물관장      2
9106  2020 한국인터넷기자상 시상식 내달 1일 개최…특별상 김성후      2

[9107 rows x 2 columns]